# nginx proxy address - http://172.17.0.1:8089

name: snippetbox
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: pawelmalak/snippet-box:latest
    pull_policy: always
    container_name: snippetbox-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - snippetbox
    ports:
      - "172.17.0.1:8089:5000"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./volumes/data/snippetbox:/data

networks:
  snippetbox:
    name: snippetbox
    external: false
